"""
Multi-Atlas Segmentation of MR Tumor Brain Images Using Low- Rank Based Image Recovery [Tang et al., 2018]
* MULTI-atlas segmentation (MAS) uses image registration to transfer label information from multiple brain atlases
to a new brain image and then performs label fusion to obtain the final segmentation result of the new brain image.
* In this paper, we propose a new low-rank method and integrate it into a new MAS framework for reliable and accurate
segmentation of MR tumor brain images.

==> Our MAS framework consists of two steps:
1) using the new low-rank method to get the recovered image from the input tumor brain image based on the information
of normal brain atlases
2) registering each normal brain atlas to the recovered image. These two steps are iterated until convergence, for
obtaining the final segmentation result.

-----------------------------------------------
SCOLOR : Specifically, weak residual error constraint is imposed on tumor regions to allow large modification in image
appearance, whereas strong residual error constraint is imposed on normal brain regions to make the distortion as small
as possible.
See Fig 2 (very similar in spirit to ours) --> define probability map from deformations + graph cut
-----------------------------------------------

Better than them ? Maybe --> we do not rely on diffeo registrations from various atlases

The synthetic tumor brain image is generated by inserting tumor(s) derived from a real T1-weighted tumor brain image in
BRATS2015. Since all the images from LPBA40 and BRATS2015 are aligned with MNI152 (182×218×182 voxels, 1 × 1 × 1 mm3
voxel size) by affine transformation at the preprocessing stage, we can simply use the image content of the tumor(s) in
the real tumor brain image from BRATS2015 to replace the image content at the same location in the selected image from
LPBA40.
"""